# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "node_modules"
    steps:
      - run: ls -al << parameters.path >>
  install:
    description: "Install dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

# Common executor for node based jobs
executors:
  node-executor:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/pixeloven

# Define jobs
jobs:
  build:
    executor: node-executor
    steps:
          # Download and cache dependencies
      - install

      # Check for pixeloven deps
      - list:
          path: node_modules/@pixeloven

        # Run build and test
      - run:
            name: Lint source
            command: yarn lint
      - run:
          name: Compile source
          command: yarn compile
      - run:
          name: Test source
          command: yarn test

       # Save artifacts
      - store_artifacts:
          path: dist
          destination: dist

      # Save coverage files to workspace
      - persist_to_workspace:
          root: /tmp/workspace
          paths: 
            - packages/**/coverage/lcov.info

  report:
    executor: node-executor
    steps:
      - attach_workspace:
          at: /tmp/workspace

      # Download and cache dependencies
      - install

      # Check for workspace
      - list:
          path: /tmp/workspace

      # Run test and report
    #   - run:
    #       name: Test source
    #       command: yarn report-coverage

workflows:
  version: 2.1
  build-and-report:
    jobs:
      - build
      - report:
          requires:
            - build
          filters:
            branches:
              only: master