# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "node_modules"
    steps:
      - run:
          name: "List << parameters.path >>"
          command: ls -al << parameters.path >>
  install:
    description: "Install dependencies"
    steps:
      - checkout
      - restore_cache:
          keys:
            - v2-dependencies-{{ checksum "package.json" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v2-dependencies-{{ checksum "package.json" }}

# Common executor for node based jobs
executors:
  node-executor:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/pixeloven

# Define jobs
jobs:
  setup:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - install

      # Check for pixeloven deps
      - list:
          path: node_modules

  lint:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - install

        # Run task
      - run:
          name: Lint source
          command: yarn lint

  build:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - install

        # Run build and test
      - run:
          name: Compile source
          command: yarn compile

       # Save artifacts
      - store_artifacts:
          path: dist
          destination: dist

  test:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - install

        # Run build and test
        # @desc This is to get around this issue https://github.com/facebook/jest/issues/1477 
      - run:
          name: Compile source
          command: yarn compile

        # Run task
      - run:
          name: Test source
          command: yarn test

      # Save project
      - persist_to_workspace:
          root: .
          paths: 
            - packages/**/coverage/lcov.info

  report:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - install

      - attach_workspace:
          at: ~/pixeloven

      # Check for pixeloven deps
      - list:
          path: packages/**/coverage/lcov.info

      # Run test and report
    #   - run:
    #       name: Test source
    #       command: yarn report-coverage

workflows:
  version: 2.1
  runner:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - test:
          requires:
            - setup
      - build:
          requires:
            - setup
      - report:
          requires:
            - test
          filters:
            branches:
              only: master