# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

# Reusable commands
commands:
  list:
    description: "List directory contents"
    parameters:
      path:
        type: string
        default: "."
    steps:
      - run:
          name: "List Directory"
          command: ls -al << parameters.path >>
  install:
    description: "Install dependencies"
    steps:
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

# Common executor for node based jobs
executors:
  node-executor:
    docker:
      - image: circleci/node:8.12
    working_directory: ~/pixeloven

# Define jobs
jobs:
  setup:
    executor: node-executor
    steps:
      # Allows us to pre-cache yarn install
      - checkout
      - install
      - list

  lint:
    executor: node-executor
    steps:
      - checkout
      - install
      - list

        # Run task
      - run:
          name: Lint source
          command: yarn lint

  build:
    executor: node-executor
    steps:
      - checkout
      - install
      - list

        # Run build and test
        # @todo Find a way to break this out into parts
      - run:
          name: Compile source
          command: yarn compile

      - run:
          name: Test source
          command: yarn test

       # Save artifacts
      - store_artifacts:
          path: packages/**/dist
          destination: dist

       # Save artifacts
      - store_artifacts:
          path: packages/**/coverage
          destination: coverage

      # Save project
      - persist_to_workspace:
          root: .
          paths: 
            - packages/**/coverage/lcov.info

  report:
    executor: node-executor
    steps:
      # Download and cache dependencies
      - checkout
      - install

      - attach_workspace:
          at: ~/pixeloven

      # Check for pixeloven deps
      - list:
          path: packages/**/coverage/lcov.info

      # Run test and report
      - run:
          name: Test source
          command: yarn report-coverage

workflows:
  version: 2.1
  runner:
    jobs:
      - setup
      - lint:
          requires:
            - setup
      - build:
          requires:
            - setup
      - report:
          requires:
            - build
          # filters:
          #   branches:
          #     only: master